print()
print("Напишите текс с новой строки: ")
my_string = input()
# my_strig = "Я сегодня научился новому"
leng = len(my_string)
print(my_string, " = ", leng, "символов")
print("Выведите его верхним регистром: ", my_string.upper())
print("Выведите его нижним регистром: ", my_string.lower())
print("Удалите все пробелы: ", my_string.replace(" ", ""))
print("Выведите первый символ: ", my_string[0:1])
print("Выведите крайний символ (1-й способ): ", my_string[-1])
print("Выведите крайний символ (2-й способ): ", my_string[24:25]) # в случае, когда известно количество символов и индексы (в данном случае их 25).
print("Выведите крайний символ (3-й способ): ", my_string.replace("Я сегодня научился новому", "у"))
a = (my_string[-1])
print("Выведите крайний символ (4-й способ): ", a)
print()
print("Конец задания.")
print()
print()
print("Дополнительная литература - https://docs.python.org/3/library/stdtypes.html#string-methods")